# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

run:
  deadline: 5m
  issues-exit-code: 1
  tests: true

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - unused
  enable-all: false
  disable-all: true
