name: ci
on:
  push:
jobs:
  lint-go:
    runs-on: ubuntu-latest
    env:
      GO_TAGS: ''
      GO111MODULE: 'on'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ".go-version"
      - name: Setup golangci-lint
        run: |-
          download=https://raw.githubusercontent.com/golangci/golangci-lint/9a8a056e9fe49c0e9ed2287aedce1022c79a115b/install.sh  # v1.52.2
          curl -sSf "$download" | sh -s v1.51.2
          ./bin/golangci-lint version
      - run: make check
  check-deps-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ".go-version"
      - run: make check-mod
  test-go:
    runs-on: ubuntu-latest
    env:
      GO_TAGS: ''
      GO111MODULE: 'on'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ".go-version"
      - run: make test
  build-go:
    runs-on: ubuntu-latest
    env:
      GO_TAGS: ''
      GO111MODULE: 'on'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ".go-version"
      - run: make dev
permissions:
  contents: read
